### ISSUE TITLE
Pagamento: No package identifier when getting value for resource number 0x00000000

### ISSUE THREAD

**Issue by mariolandossa** [jhonathanqz/stone_smart_flutter#29]
Bom dia, ao final da aprovação o Response está quebrando, consegue me dar uma dica do que está errado, de qual Config ele está falando ?

I/flutter ( 7535): ***onFinishedResponse: {"aid":"A0000000031010","amount":"101","arcq":"E1DB026FE7E5BXXX","authorizationCode":"5823XX","cardBrand":"VISA","cardBrandId":2,"cardHolderNumber":"XXXXXX****XXXX","date":"2024-07-25","entryMode":"CONTACTLESS","idFromBase":26,"initiatorTransactionKey":"L3-1721912835966","isBuildResponse":1,"isPrinterRequest":true,"manufacture":"Positivo","messageFromAuthorize":"Aprovado","method":"transaction","result":0,"saleAffiliationKey":"XXXXXXXXXXXXXXXXXX","serialNumber":"XXXXXX","time":"10:07:15","transactionKey":"XXXXXXXXX","transactionObject":"TransactionObject{idFromBase\u003d26, amount\u003d\u0027101\u0027, requestId\u003d\u0027null\u0027, emailSent\u003d\u0027null\u0027, timeToPassTransaction\u003d\u0027\u0027, initiatorTransactionKey\u003d\u0027L3-1721912835966\u0027, recipientTransactionIdentification\u003d\u002730741081582359\u0027, cardHolderNumber\u003d\u0027417400****0736\u0027, cardHolderName\u003d\u0027PAYWAVE/VISA\u0027, date\u003d\u00272024-07-25\u0027, time
W/ResourceType( 7535): No package identifier when getting value for resource number 0x00000000
W/ResourceType( 7535): No package identifier when getting value for resource number 0x00000000
I/System.out( 7535): Config App not found
W/ResourceType( 7535): No package identifier when getting value for resource number 0x00000000
W/ResourceType( 7535): No package identifier when getting value for resource number 0x00000000
W/ResourceType( 7535): No package identifier when getting value for resource number 0x00000000
I/System.out( 7535): Config App not found

**Comment by jhonathanqz** [comment]
Cara, aparentemente o plugin parece estar tudo ok, pois está transacionando. (Você recebeu o response completo da Stone)... esse `I/System.out( 7535): Config App not found` parece ser de sua aplicação

**Comment by mariolandossa** [comment]
Esse é o log do app exemplo que vem no repositorio
